name = "SpectralWaves"
uuid = "1c8cf7b8-223b-484e-98e7-6240f1484c2c"
authors = ["Maciej Paprota <mapap@ibwpan.gda.pl> and contributors"]
version = "1.0.0-DEV"

[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"

[compat]
CairoMakie = "0.13.1"
LinearAlgebra = "1.11.0"
ProgressMeter = "1.10.2"
julia = "1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
